Repository Shubhanshu-1507/Sourcecode, pull requests merged in 2022-10, with the labels that each got.

#7 Create 5-AddSubMultDivUserDefinedNumber.c
  C_Basic_Problems/Sheet_1/5-AddSubMultDivUserDefinedNumber.c
Labels: hactoberfest-accepted, hactoberfest2022, Hactoberfest

#9 Create 6-SimpleInterestOfTwoUserDefinedNumber.c
  C_Basic_Problems/Sheet_1/6-SimpleInterestOfTwoUserDefinedNumber.c
Labels: hactoberfest-accepted, hactoberfest2022, Hactoberfest

#15 Create 9-CubeOfUserDefinedNumber.c
  C_Basic_Problems/Sheet_1/9-CubeOfUserDefinedNumber.c
Labels: hactoberfest-accepted, hactoberfest2022, Hactoberfest

#19 Create 1-ProgramToDisplayANumber.c
  Sheet_2/1-ProgramToDisplayANumber.c
Labels: hactoberfest-accepted, hactoberfest2022, Hactoberfest

#21 Create 1-ProgramToDisplayANumber.c
  C_Basic_Problems/Sheet_2/1-ProgramToDisplayANumber
Labels: hactoberfest-accepted, hactoberfest2022, Hactoberfest

#27 CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hactoberfest-accepted, hactoberfest2022, Hactoberfest

#29 Swapping without using third variable
  C_Basic_Problems/Sheet_1/SwappingWithoutThirdVariable.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#34 Create 11-FibonacciSeries.c
  C_Basic_Problems/Sheet_1/11-FibonacciSeries.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#39 Create 4-CheckPosOrNot.c
  C_Basic_Problems/Sheet_2/4-CheckPosOrNot.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#37 Create 3-CheckVowelOrConsonant.c
  C_Basic_Problems/Sheet_2/3-CheckVowelOrConsonant.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#41 Create 5-ProgramToRelate
  5-ProgramToRelate.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#43 Create 6-GreaterOfThree.c
  6-GreaterOfThree.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#45 Create 7-CheckLeapYear.c
  7-CheckLeapYear.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#47 Create 10-EvenOrOdd.c
  10-EvenOrOdd.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#49 Create 11-RootsToFindQuadraticEquation.c
  11-RootsToFindQuadraticEquation.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#51 Create 5-ProgramToRelate.c
  C_Basic_Problems/Sheet_2/5-ProgramToRelate.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#52 Create 6-GreaterOfThree.c
  C_Basic_Problems/Sheet_2/6-GreaterOfThree.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#54 Create 7-CheckLeapYear.c
  C_Basic_Problems/Sheet_2/7-CheckLeapYear.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#56 Create 10-EvenOrOdd.c
  C_Basic_Problems/Sheet_2/10-EvenOrOdd.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#59 Create 11-RootsToFindQuadraticEquation.c
  C_Basic_Problems/Sheet_2/11-RootsToFindQuadraticEquation.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#61 Create 1-GreaterBetweenTwoNumbers.c
  C_Basic_Problems/Sheet_3/1-GreaterBetweenTwoNumbers.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#63 Create 2-GreaterOfThree.c
  C_Basic_Problems/Sheet_3/2-GreaterOfThree.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#65 Create 3-AndOrXOR.c
  C_Basic_Problems/Sheet_3/3-AndOrXOR.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#67 Create 4-SimpleCalculator.c
  C_Basic_Problems/Sheet_3/4-SimpleCalculator.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#69 Create 5-WeekdayNumAndWeekdayName.c
  C_Basic_Problems/Sheet_3/5-WeekdayNumAndWeekdayName.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#71 Create 6-PrintGenderName.c
  C_Basic_Problems/Sheet_3/6-PrintGenderName.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#73 Create 7-NumberOfDaysInAMonth.c
  C_Basic_Problems/Sheet_3/7-NumberOfDaysInAMonth.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#74 Create 14
  C_Basic_Problems/Sheet_4/Series/14
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#76 Create 15
  C_Basic_Problems/Sheet_4/Series/15.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#78 Create 16
  C_Basic_Problems/Sheet_4/Series/16.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#79 Create 17
  C_Basic_Problems/Sheet_4/Series/17.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#83 Create 19
  C_Basic_Problems/Sheet_4/Series/19.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#85 Create 20
  C_Basic_Problems/Sheet_4/Series/20.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#89 Create 22
  C_Basic_Problems/Sheet_4/Series/22.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#92 Create 1
  C_Basic_Problems/Sheet_4/patterns/1
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#94 Create 2
  C_Basic_Problems/Sheet_4/2
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#95 Create 3
  C_Basic_Problems/Sheet_4/3
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#96 Create 5
  C_Basic_Problems/Sheet_4/5
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#97 Create 6
  C_Basic_Problems/Sheet_4/6
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#98 Create 7
  C_Basic_Problems/Sheet_4/7
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#99 Create 8
  C_Basic_Problems/Sheet_4/8
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#100 Create 9
  C_Basic_Problems/Sheet_4/9
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#101 Create 10
  C_Basic_Problems/Sheet_4/10
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#102 Create 11
  C_Basic_Problems/Sheet_4/11
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#103 Create 12
  C_Basic_Problems/Sheet_4/12
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#104 Create 1
  C_Basic_Problems/Sheet_4/1.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#106 patterns
  C_Basic_Problems/Sheet_4/patterns/10.c
  C_Basic_Problems/Sheet_4/patterns/11.c
  C_Basic_Problems/Sheet_4/patterns/12.c
  C_Basic_Problems/Sheet_4/patterns/2.c
  C_Basic_Problems/Sheet_4/patterns/3.c
  C_Basic_Problems/Sheet_4/patterns/4.c
  C_Basic_Problems/Sheet_4/patterns/5.c
  C_Basic_Problems/Sheet_4/patterns/6.c
  C_Basic_Problems/Sheet_4/patterns/7.c
  C_Basic_Problems/Sheet_4/patterns/8.c
  C_Basic_Problems/Sheet_4/patterns/9.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#108 Create 1_firstTenIntsUsingWhile
  C_Basic_Problems/Sheet_4/1_34/1_firstTenIntsUsingWhile
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#109 Create 2_firstTenReverseNumberUsingDoWhile.c
  C_Basic_Problems/Sheet_4/1_34/2_firstTenReverseNumberUsingDoWhile.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#111 Create 3_name10Times
  C_Basic_Problems/Sheet_4/1_34/3_name10Times.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#113 Create 4_evenNumbersBetween1to50.c
  C_Basic_Problems/Sheet_4/1_34/4_evenNumbersBetween1to50.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#115 Create 5_first20Odd.c
  C_Basic_Problems/Sheet_4/1_34/5_first20Odd.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#117 Create 6_sumOfFirst10Numbers.c
  C_Basic_Problems/Sheet_4/1_34/6_sumOfFirst10Numbers.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#119 Create 7_TableGeneration.c
  C_Basic_Problems/Sheet_4/1_34/7_TableGeneration.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#121 Create 8_SumOfAllEvenNum1to100.c
  C_Basic_Problems/Sheet_4/1_34/8_SumOfAllEvenNum1to100.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#123 Create 9_n^m.c
  C_Basic_Problems/Sheet_4/1_34/9_n^m.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#125 Create 10_maxAndMin.c
  C_Basic_Problems/Sheet_4/1_34/10_maxAndMin.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#127 Add files via upload
  C_Basic_Problems/Sheet_4/1_34/11_factorialOfNumber.c
  C_Basic_Problems/Sheet_4/1_34/12_sumOfNseries.c
  C_Basic_Problems/Sheet_4/1_34/13_sumOfAlPlusMinusSeries.c
  C_Basic_Problems/Sheet_4/1_34/23_CheckPrime.c
  C_Basic_Problems/Sheet_4/1_34/24_fibonacciSeries.c
  C_Basic_Problems/Sheet_4/1_34/25_countAllPrimeNumbers1toN.c
  C_Basic_Problems/Sheet_4/1_34/26_HCFofTwoNumbers.c
  C_Basic_Problems/Sheet_4/1_34/27_LCFofTwoNumbers.c
  C_Basic_Problems/Sheet_4/1_34/29_PrintInVertically.c
  C_Basic_Problems/Sheet_4/1_34/30_reverseOrder.c
  C_Basic_Problems/Sheet_4/1_34/31_sumOfDigit.c
  C_Basic_Problems/Sheet_4/1_34/32_sumUntilsingle.c
  C_Basic_Problems/Sheet_4/1_34/33_checkArmstrong.c
  C_Basic_Problems/Sheet_4/1_34/34_checkPalindrome.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#87 Create 21
  C_Basic_Problems/Sheet_4/Series/21.c
Labels: help wanted, HACKTOBERFEST-ACCEPTED, hacktoberfest2022

#58 Create min_cost.cpp
  min_cost.cpp
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest

#93 Create traversepython.py
  traversepython.py
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest2022, hacktoberfest
